CREATE TABLE IF NOT EXISTS projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    description TEXT,
    tech_stack  VARCHAR(500),
    github_url  VARCHAR(500),
    demo_url    VARCHAR(500),
    image_url   VARCHAR(500),
    featured    BOOLEAN       NOT NULL DEFAULT false,
    created_at  TIMESTAMP     NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS skills (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    category VARCHAR(100),
    level    INTEGER
);

CREATE TABLE IF NOT EXISTS contact_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    message    TEXT         NOT NULL,
    read       BOOLEAN      NOT NULL DEFAULT false,
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Default admin user: password is "admin" (BCrypt)
INSERT INTO users (username, password)
VALUES ('admin', '$2b$10$ui3kQkpG6qbUVFscudnROevwRWOPw4KoZAz66woXHkQqdlWal/IcC');
